# Generated by Django 3.2.25 on 2025-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annual_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('cover_img_link', models.TextField()),
                ('review', models.TextField()),
                ('edition_number', models.IntegerField()),
            ],
        ),
    ]
